# Generated by Django 6.0.8 on 2026-09-18 04:56

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('phone_number', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='Use international format, for example +256700123456.', regex='^\\+[1-9][0-9]{7,14}$')])),
                ('sms_opt_in', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('code', models.SlugField(unique=True)),
                ('location', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('warning', 'Warning'), ('critical', 'Critical')], default='warning', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('investigating', 'Investigating'), ('monitoring', 'Monitoring recovery'), ('resolved', 'Resolved')], db_index=True, default='open', max_length=20)),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('recovery_verified_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_incidents', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='api.site')),
            ],
            options={
                'ordering': ['-opened_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient_phone', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='Use an international phone number.', regex='^\\+[1-9][0-9]{7,14}$')])),
                ('message_type', models.CharField(choices=[('outage', 'Outage notice'), ('update', 'Progress update'), ('recovery', 'Service restored')], max_length=20)),
                ('message', models.TextField()),
                ('approval_status', models.CharField(choices=[('pending', 'Pending approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_status', models.CharField(choices=[('not_sent', 'Not sent'), ('queued', 'Queued'), ('sent', 'Accepted by SMS provider'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='not_sent', max_length=20)),
                ('provider_message_id', models.CharField(blank=True, db_index=True, max_length=200)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_notifications', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='api.customer')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='api.incident')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('code', models.SlugField(max_length=80, unique=True)),
                ('device_type', models.CharField(choices=[('router', 'Router'), ('switch', 'Switch'), ('access_point', 'Access point'), ('other', 'Other')], default='router', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='api.site')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='api.site'),
        ),
        migrations.CreateModel(
            name='TelemetryReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('is_reachable', models.BooleanField()),
                ('latency_ms', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('packet_loss_percent', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_simulated', models.BooleanField(default=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='readings', to='api.device')),
            ],
            options={
                'ordering': ['-recorded_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alert_type', models.CharField(choices=[('device_down', 'Device unreachable'), ('high_latency', 'High latency'), ('packet_loss', 'Packet loss')], max_length=30)),
                ('severity', models.CharField(choices=[('warning', 'Warning'), ('critical', 'Critical')], default='warning', max_length=20)),
                ('message', models.TextField()),
                ('detected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('cleared_at', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alerts', to='api.device')),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alerts', to='api.incident')),
                ('reading', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='api.telemetryreading')),
            ],
            options={
                'ordering': ['-detected_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('site', 'phone_number'), name='unique_customer_phone_per_site'),
        ),
        migrations.AddIndex(
            model_name='telemetryreading',
            index=models.Index(fields=['device', '-recorded_at'], name='api_telemet_device__8e4ad5_idx'),
        ),
        migrations.AddConstraint(
            model_name='telemetryreading',
            constraint=models.CheckConstraint(condition=models.Q(('latency_ms__isnull', True), ('latency_ms__gte', 0), _connector='OR'), name='telemetry_latency_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='telemetryreading',
            constraint=models.CheckConstraint(condition=models.Q(('packet_loss_percent__gte', 0), ('packet_loss_percent__lte', 100)), name='telemetry_packet_loss_range'),
        ),
    ]
