# Generated by Django 6.0.8 on 2026-09-18 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='affected_sites',
            field=models.ManyToManyField(blank=True, related_name='affected_incidents', to='api.site'),
        ),
        migrations.AddField(
            model_name='incident',
            name='confidence_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='probable_cause',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='shared_dependency',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
