# Generated by Django 6.0.8 on 2026-09-18 15:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_add_incident_correlation_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerNetworkReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sender_phone', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='Use international format, for example +256700123456.', regex='^\\+[1-9][0-9]{7,14}$')])),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('received', 'Received'), ('matched', 'Matched'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], db_index=True, default='received', max_length=20)),
                ('link_id', models.CharField(blank=True, db_index=True, max_length=200)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='network_reports', to='api.customer')),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_network_reports', to='api.incident')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_network_reports', to='api.site')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
