# Generated by Django 6.0.8 on 2026-09-18 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_add_incident_timeline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='delivery_status',
            field=models.CharField(choices=[('not_sent', 'Not sent'), ('dry_run', 'Dry run only'), ('queued', 'Queued'), ('sent', 'Accepted by SMS provider'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='not_sent', max_length=20),
        ),
    ]
