# Generated by Django 6.0.8 on 2026-09-18 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_add_notification_dry_run_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='site_type',
            field=models.CharField(choices=[('tower', 'Tower'), ('pop', 'Point of presence'), ('data_center', 'Data centre'), ('exchange', 'Exchange'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
