# Generated by Django 6.0.8 on 2026-09-18 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_add_site_type'),
        ('api', '0005_customernetworkreport'),
    ]

    operations = [
    ]
