# Generated by Django 6.0.8 on 2026-09-18 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_merge_0005_add_site_type_0005_customernetworkreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='customernetworkreport',
            name='updates_opted_in',
            field=models.BooleanField(default=True),
        ),
    ]
