# Generated by Django 6.0.8 on 2026-09-19 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_merge_0005_add_site_type_0005_customernetworkreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='escalated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='escalation_level',
            field=models.CharField(choices=[('none', 'Not escalated'), ('level_1', 'Level 1'), ('level_2', 'Level 2'), ('level_3', 'Level 3')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='incident',
            name='escalation_status',
            field=models.CharField(choices=[('not_escalated', 'Not escalated'), ('escalated', 'Escalated'), ('acknowledged', 'Acknowledged'), ('dispatched', 'Technician dispatched')], default='not_escalated', max_length=30),
        ),
        migrations.AddField(
            model_name='incident',
            name='escalation_team',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='incidentevent',
            name='event_type',
            field=models.CharField(choices=[('detected', 'Incident detected'), ('assignment', 'Engineer assignment'), ('escalation', 'Incident escalation'), ('status', 'Status change'), ('note', 'Investigation note'), ('recovery', 'Recovery update'), ('resolved', 'Incident resolved')], max_length=30),
        ),
    ]
